### ISSUE TITLE
can't seem to start training with 1 and 2 Tesla V100 gpus 

### ISSUE THREAD

**Issue by bit-scientist** [open-mmlab/mmaction2#1266]
- [x] I have searched related issues but cannot get the expected help.
- [x] I have read the [FAQ documentation](https://mmaction2.readthedocs.io/en/latest/faq.html) but cannot get the expected help.

Today I had an opportunity to spare some time to train my custom dataset prepared by referring to [Custom Dataset Training with PoseC3D](https://github.com/open-mmlab/mmaction2/blob/master/configs/skeleton/posec3d/custom_dataset_training.md). But it looks like there are some things to consider when having 1 or many gpus. 

```
------------------------------------------------------------
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.1
OpenCV: 4.5.3
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMAction2: 0.18.0+
------------------------------------------------------------
```

Assume `5class_slowonly_r50_u48_240e_ntu120_xsub_keypoint.py` is my config file with necessary modifications. 
Initially, I wanted to train simply with these, one at a time:

1. `python tools/train.py /home/office/projects/openmmaction2/configs/skeleton/posec3d/5class_slowonly_r50_u48_240e_ntu120_xsub_keypoint.py` 
2. `python tools/train.py /home/office/projects/openmmaction2/configs/skeleton/posec3d/5class_slowonly_r50_u48_240e_ntu120_xsub_keypoint.py  --validate --test-best --seed 0 --deterministic`
3. `python tools/train.py /home/office/projects/openmmaction2/configs/skeleton/posec3d/5class_slowonly_r50_u48_240e_ntu120_xsub_keypoint.py  --validate --test-best --gpus 1 --seed 0 --deterministic`

the above commands output identical errors as below:

```
2021-11-12 09:45:20,998 - mmaction - INFO - workflow: [('train', 10)], max: 300 epochs
/opt/conda/conda-bld/pytorch_1631630742027/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1631630742027/work/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 177, in main
    meta=meta)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmaction/apis/train.py", line 165, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmaction/models/recognizers/base.py", line 297, in train_step
    loss, log_vars = self._parse_losses(losses)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmaction/models/recognizers/base.py", line 243, in _parse_losses
    log_vars[loss_name] = loss_value.item()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1631630742027/work/c10/cuda/CUDACachingAllocator.cpp:1055 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f5346b70a22 in /home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x109a3 (0x7f5346dd29a3 in /home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1a7 (0x7f5346dd4047 in /home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f5346b5a5a4 in /home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0xa2baf2 (0x7f5397244af2 in /home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0xa2bb91 (0x7f5397244b91 in /home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7f53bd34ebf7 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```

When `--gpus 2`, it's a little different as expected: 

```
2021-11-12 09:50:04,223 - mmaction - INFO - workflow: [('train', 10)], max: 300 epochs
Traceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 177, in main
    meta=meta)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmaction/apis/train.py", line 165, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/office/anaconda3/envs/openmm-lab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 55, in train_step
    ('MMDataParallel only supports single GPU training, if you need to'
AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.
```

Does someone know how to correctly set these args? Maybe there are compatibility issues that have that require to install specific package versions?
As checked above, I searched the web for a solution, but they are either outdated or unrelated to my case.

**Comment by kennymckormick** [comment]
A little bit weird, would you please try distributed training with `tools/dist_train.sh`?

**Comment by kennymckormick** [comment]
You can use distributed training even with one GPU.

**Comment by bit-scientist** [comment]
> You can use distributed training even with one GPU.

Thanks, I could run `./tools/dist_train.sh /home/e2on/projects/sb_openmmaction2/configs/skeleton/posec3d/5class_cfg.py 2 --validate --deterministic --test-best` command it and started training. 

P.S. As for `RuntimeError: CUDA error: device-side assert triggered` for the above 3 commands, it turns out that the class labels must strictly follow `0,1,2,3,...,c` naming convention.  I think it has got nothing to do with the script, just some CUDA quirk 😄

**Comment by Laowai01** [comment]
In mmaction2 directory

`bash ./tools/dist_train.sh ./configs/skeleton/posec3d/5class_cfg.py 2 --validate --deterministic --test-best`

solves the issues for 2 or more gpus (need to parse the # number of gpu you want to use to training)

**Comment by amdddr** [comment]
You can try to specify the  ‘--seed  12345’ and  ‘--deterministic True ’parameters simultaneously. It works well for multi-GPUS in 1 machine.
