### ISSUE TITLE
Docker Image: cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmaction2#767]
Hi! 
I am trying to get started using the [docker image](https://github.com/open-mmlab/mmaction2/blob/master/docker/Dockerfile). However, because I have 3090 GPUs I am getting the following warning: 

```
GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
```

After checking out [this ](https://github.com/pytorch/pytorch/issues/45028) and [this ](https://github.com/pytorch/pytorch/issues/45021) issue from Pytorch it seems that one should be using the following versions of PyTorch and Cuda:

```
ARG PYTORCH="1.8.1"
ARG CUDA="11.1"
ARG CUDNN="8"
```

So, I did this replacement (along with `ENV TORCH_CUDA_ARCH_LIST="8.0+PTX"`) but unfortunately, I get another error, namely 
`cannot read property 'url' of undefined` and the building of the image fails. 

Is there any other thing I need to replace in the docker image or `mmaction2` doesn't currently work with the above-mentioned configs?

**Comment by congee524** [comment]
Maybe you also need to change the install command of mmcv.

And you should use pytorch 1.8.0, since there is no available pt1.8.1 docker image in [pytorch/pytorch](https://hub.docker.com/r/pytorch/pytorch/tags)

```
ARG PYTORCH="1.8.0"
ARG CUDA="11.1"
ARG CUDNN="8"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 8.0+PTX"

RUN pip install mmcv-full==1.3.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
```

Pls try to modify your dockerfile as above and I'll be waiting for your response.

**Comment by rlleshi** [comment]
Thanks for getting back! Unfortunately, the error still persists.

**Comment by congee524** [comment]
Hey, I have no device with 3090, but I build an image from the modified dockerfile and everything works well. Because I can't reproduce your problem, I may not be able to provide more help. I guess it may have something to do with the `protainer`.

**Comment by innerlee** [comment]
It looks like a javascript error, so I guess portainer hides the real problem.

**Comment by rlleshi** [comment]
Ok, definitely a `portainer` error. I build the image locally, uploaded it in the docker hub, and then used it through a stack from portainer (in case anyone else will come across this), and it's working now. Looks like portainer frontend has multiple issues with building images.

Please consider updating the docker file with the above-mentioned changes as they solve mismatching `GeForce RTX 3090` with `CUDA` & `PyTorch` version.

**Comment by congee524** [comment]
Thanks for your advice. The docker file will remain as it is for a while because we haven't tested Pytorch 1.8 on MMAction2 now.
